package com.tekcapsule.insight.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.tekcapsule.core.domain.AggregateRoot;
import com.tekcapsule.core.domain.BaseDomainEntity;
import lombok.*;


@Data
@JsonIgnoreProperties(ignoreUnknown = true)
@EqualsAndHashCode(callSuper = true)
@DynamoDBTable(tableName = "Insights")
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Insights extends BaseDomainEntity implements AggregateRoot {
    @DynamoDBHashKey(attributeName="insightsId")
    @DynamoDBAutoGeneratedKey
    private String insightsId;
    @DynamoDBAttribute(attributeName = "stocks")
    private Stocks stocks;
    @DynamoDBAttribute(attributeName = "news")
    private News news;


}

